server.port=${PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/tarefas}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tarefas}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tarefas123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
